# Generated by Django 4.1.1 on 2022-10-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Calificacion', models.IntegerField()),
                ('Pais', models.CharField(max_length=200)),
            ],
        ),
    ]
